name: pitask

description: "Home Services Provider App trade cropto"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  cupertino_icons: any
  shimmer: ^3.0.0
  intl_phone_field: ^3.2.0
  webview_flutter: ^4.10.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  firebase_messaging: ^15.1.6
  #google_api_headers: ^4.4.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  google_maps_flutter: ^2.10.0
  map_launcher: ^3.5.0
  #google_maps_place_picker_mb: ^3.1.2 // Ajustar ou achar outra biblioteca compatível

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/
    - config/
